JADE-48: The stack trace is no longer saved in the database, instead it is logged on the server using slf4j.  Information is added to the trace so we can identify the client from which the error came from.  See example:
2008-09-25 11:42:22,115 - ERROR - rumentExecutionServiceImpl - Instrument runner error encountered on SphygmoCor 1 (Vendor=AtCor Medical, Model=SphygmoCor, Barcode=sphygmoCor1) by user The ONYX Administrator (username=administrator) :
2008-09-25 11:42:22,130 - ERROR - rumentExecutionServiceImpl - Error stack trace:
java.lang.RuntimeException: No device output found
        at org.obiba.onyx.jade.instrument.atcor.SphygmoCorInstrumentRunner.run(SphygmoCorInstrumentRunner.java:123)
        at org.obiba.onyx.jade.client.JnlpClient.main(JnlpClient.java:42)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.sun.javaws.Launcher.executeApplication(Unknown Source)
        at com.sun.javaws.Launcher.executeMainClass(Unknown Source)
        at com.sun.javaws.Launcher.doLaunchApp(Unknown Source)
        at com.sun.javaws.Launcher.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)